export const FETCHING_PHOTOS = 'FETCHING_PHOTOS';
export const FETCHING_PHOTOS_SUCCESS = 'FETCHING_PHOTOS_SUCCESS';
export const FETCHING_PHOTOS_FAIL = 'FETCHING_PHOTOS_FAIL';

export const FETCHING_PHOTO = 'FETCHING_PHOTO';
export const FETCHING_PHOTO_SUCCESS = 'FETCHING_PHOTO_SUCCESS';
export const FETCHING_PHOTO_FAIL = 'FETCHING_PHOTO_FAIL';

export const FETCHING_PROFILE = 'FETCHING_PROFILE';
export const FETCHING_PROFILE_SUCCESS = 'FETCHING_PROFILE_SUCCESS';
export const FETCHING_PROFILE_FAIL = 'FETCHING_PROFILE_FAIL';

export const FETCHING_TEAMS = 'FETCHING_TEAMS';
export const FETCHING_TEAMS_SUCCESS = 'FETCHING_TEAMS_SUCCESS';
export const FETCHING_TEAMS_FAIL = 'FETCHING_TEAMS_FAIL';

export const FETCHING_TEAM = 'FETCHING_TEAM';
export const FETCHING_TEAM_SUCCESS = 'FETCHING_TEAM_SUCCESS';
export const FETCHING_TEAM_FAIL = 'FETCHING_TEAM_FAIL';

export const FETCHING_PLAYERS = 'FETCHING_PLAYERS';
export const FETCHING_PLAYERS_SUCCESS = 'FETCHING_PLAYERS_SUCCESS';
export const FETCHING_PLAYERS_FAIL = 'FETCHING_PLAYERS_FAIL';

export const FETCHING_PLAYER = 'FETCHING_PLAYER';
export const FETCHING_PLAYER_SUCCESS = 'FETCHING_PLAYER_SUCCESS';
export const FETCHING_PLAYER_FAIL = 'FETCHING_PLAYER_FAIL';
